spring.application.name=inventario
# Configuracion de conexion a la Base de Datos H2 persistente en archivo
spring.datasource.url=jdbc:h2:file:./data/inventario
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Dialecto e instruccion para crear/actualizar las tablas automaticamente
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Activar la consola web de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console